# Generated by Django 5.2.4 on 2025-08-28 17:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'users',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Descrição')),
                ('sector_name', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Setor')),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('MED', 'Média'), ('HIGH', 'Alta')], max_length=4, verbose_name='Prioridade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('status', models.CharField(choices=[('TODO', 'A fazer'), ('DOING', 'Fazendo'), ('DONE', 'Pronto')], default='TODO', max_length=5, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.user', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_task_status'), models.Index(fields=['priority'], name='idx_task_priority'), models.Index(fields=['sector_name'], name='idx_task_sector')],
            },
        ),
    ]
